### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by Cyl18** [Monodesu/osucat-reborn#25]
我想请教一下那1300行的图片渲染是怎么写出来的 手工一个一个找点连线然后写的？😀

**Comment by Monodesu** [comment]
很不巧 是这样
是chingc和我一起完成的

**Comment by Monodesu** [comment]
新的仓库 重构了代码 删掉src内除main.hpp之外的文件也可当作单独的CQHTTP SDK来使用
https://github.com/Monodesu/osucat
